import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  // console.log(data);
  return (
    <>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {
          data.map(ev => <a key={ev.id} href={`/events/${ev.id}`}>
            <Image width={200} height={200} alt={ev.title} src={ev.image} /><h3>{ev.title}</h3><p>{ev.description}</p>
          </a>)
        }

      </main>
    </>
  )
}


export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json');

  return {
    props: {
      data: events_categories
    }
  }
} 