import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <h2>Events is Dhaka</h2>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam velit corrupti officiis hic, cum voluptate dolore illum mollitia aliquam necessitatibus ducimus, veritatis blanditiis error obcaecati rerum? Velit odit veniam quo.</p>
        </a>
        <a href="">
          <h2>Events is London</h2>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam velit corrupti officiis hic, cum voluptate dolore illum mollitia aliquam necessitatibus ducimus, veritatis blanditiis error obcaecati rerum? Velit odit veniam quo.</p>
        </a>
        <a href="">
          <h2>Events is Paris</h2>
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam velit corrupti officiis hic, cum voluptate dolore illum mollitia aliquam necessitatibus ducimus, veritatis blanditiis error obcaecati rerum? Velit odit veniam quo.</p>
        </a>
      </main>
    </>
  )
}
